// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {Test} from "forge-std/Test.sol";
import {CreditCertificate, IGroth16Verifier} from "../src/CreditCertificate.sol";

/// @notice Test double for the autogenerated Groth16 verifier — the actual ZK math is
/// covered by contracts/circom-credit-certificate/test/creditCertificate.test.mjs (real
/// proof generation and verification against the compiled circuit); these Foundry tests
/// only need to know "does CreditCertificate.sol react correctly to a valid/invalid proof".
contract MockGroth16Verifier is IGroth16Verifier {
    bool public shouldVerify = true;

    function setShouldVerify(bool v) external {
        shouldVerify = v;
    }

    function verifyProof(uint256[2] calldata, uint256[2][2] calldata, uint256[2] calldata, uint256[5] calldata)
        external
        view
        override
        returns (bool)
    {
        return shouldVerify;
    }
}

contract CreditCertificateTest is Test {
    CreditCertificate certificate;
    MockGroth16Verifier verifier;

    address owner = makeAddr("owner");
    address bodega = makeAddr("bodega");
    address randomWallet = makeAddr("randomWallet");

    uint256 constant ORACLE_AX = 111;
    uint256 constant ORACLE_AY = 222;

    function setUp() public {
        verifier = new MockGroth16Verifier();
        vm.prank(owner);
        certificate = new CreditCertificate(owner, verifier);
        vm.prank(owner);
        certificate.setOraclePubKey(ORACLE_AX, ORACLE_AY);
    }

    function _publicSignals(uint256 threshold, uint256 issuedAt) internal view returns (uint256[5] memory) {
        return [threshold, uint256(uint160(bodega)), ORACLE_AX, ORACLE_AY, issuedAt];
    }

    function _dummyProof() internal pure returns (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c) {
        a = [uint256(1), uint256(2)];
        b = [[uint256(3), uint256(4)], [uint256(5), uint256(6)]];
        c = [uint256(7), uint256(8)];
    }

    function test_OnlyOwnerCanSetOraclePubKey() public {
        vm.prank(randomWallet);
        vm.expectRevert();
        certificate.setOraclePubKey(1, 2);
    }

    function test_RevertWhen_SettingZeroPubKey() public {
        vm.prank(owner);
        vm.expectRevert(CreditCertificate.ZeroPubKey.selector);
        certificate.setOraclePubKey(0, 0);
    }

    function test_SubmitCertificateStoresThresholdAndExpiry() public {
        vm.warp(1_000_000);
        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c) = _dummyProof();
        certificate.submitCertificate(a, b, c, _publicSignals(700, block.timestamp));

        assertEq(certificate.getCertifiedThreshold(bodega), 700);
        (, uint256 expiresAt) = certificate.certificates(bodega);
        assertEq(expiresAt, block.timestamp + certificate.VALIDITY_PERIOD());
    }

    function test_RevertWhen_ProofInvalid() public {
        verifier.setShouldVerify(false);
        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c) = _dummyProof();
        vm.expectRevert(CreditCertificate.InvalidProof.selector);
        certificate.submitCertificate(a, b, c, _publicSignals(700, block.timestamp));
    }

    function test_RevertWhen_OraclePubKeyMismatch() public {
        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c) = _dummyProof();
        uint256[5] memory signals = [uint256(700), uint256(uint160(bodega)), uint256(999), ORACLE_AY, block.timestamp];
        vm.expectRevert(CreditCertificate.UntrustedOracle.selector);
        certificate.submitCertificate(a, b, c, signals);
    }

    function test_RevertWhen_IssuedAtInFuture() public {
        vm.warp(1_000_000);
        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c) = _dummyProof();
        vm.expectRevert(CreditCertificate.AttestationInFuture.selector);
        certificate.submitCertificate(a, b, c, _publicSignals(700, block.timestamp + 1));
    }

    function test_RevertWhen_IssuedAtTooOld() public {
        vm.warp(1_000_000);
        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c) = _dummyProof();
        uint256 tooOld = block.timestamp - certificate.MAX_ATTESTATION_AGE() - 1;
        vm.expectRevert(CreditCertificate.AttestationTooOld.selector);
        certificate.submitCertificate(a, b, c, _publicSignals(700, tooOld));
    }

    function test_CertificateExpiresAfterValidityPeriod() public {
        vm.warp(1_000_000);
        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c) = _dummyProof();
        certificate.submitCertificate(a, b, c, _publicSignals(700, block.timestamp));
        assertEq(certificate.getCertifiedThreshold(bodega), 700);

        vm.warp(block.timestamp + certificate.VALIDITY_PERIOD() + 1);
        assertEq(certificate.getCertifiedThreshold(bodega), 0);
    }

    function test_ResubmittingOverwritesPreviousCertificate() public {
        vm.warp(1_000_000);
        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c) = _dummyProof();
        certificate.submitCertificate(a, b, c, _publicSignals(500, block.timestamp));
        assertEq(certificate.getCertifiedThreshold(bodega), 500);

        certificate.submitCertificate(a, b, c, _publicSignals(900, block.timestamp));
        assertEq(certificate.getCertifiedThreshold(bodega), 900);
    }
}
