// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {Script, console} from "forge-std/Script.sol";
import {Groth16Verifier} from "../src/CreditCertificateVerifier.sol";
import {CreditCertificate, IGroth16Verifier} from "../src/CreditCertificate.sol";

/// @notice Deploys the autogenerated Groth16 verifier (from
/// contracts/circom-credit-certificate, `snarkjs zkey export solidityverifier`) and
/// CreditCertificate.sol on top of it. Owner starts as the deployer — still needs
/// `setOraclePubKey(ax, ay)` after this, with the EdDSA-BabyJubJub pubkey the ZK oracle
/// service prints (see frontend/app/api/credit-certificate/attest, ZK_ORACLE_PRIVATE_KEY).
///
/// Usage:
///   forge script script/DeployCreditCertificate.s.sol:DeployCreditCertificate \
///     --rpc-url arbitrum_sepolia --broadcast --verify -vvvv
contract DeployCreditCertificate is Script {
    function run() external {
        uint256 deployerKey = vm.envUint("PRIVATE_KEY");
        address deployer = vm.addr(deployerKey);

        vm.startBroadcast(deployerKey);

        Groth16Verifier verifier = new Groth16Verifier();
        CreditCertificate certificate = new CreditCertificate(deployer, IGroth16Verifier(address(verifier)));

        vm.stopBroadcast();

        console.log("Groth16Verifier deployed at:", address(verifier));
        console.log("CreditCertificate deployed at:", address(certificate));
        console.log("Still needed: certificate.setOraclePubKey(ax, ay) with the ZK oracle's EdDSA pubkey");
    }
}
